language: node_js
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
node_js:
  - 7
  - 10
script:
  - yarn lint
  - yarn test
cache: yarn
